power_budget: 232000

regions:
- region_id: 0
  region_name: westus_chiron
  region_cluster: dgx-a100
  arbiter: chiron_arbiter
  model_endpoints:
  - model_endpoint_id: 0
    model_name: A-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 1
    model_name: A
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 2
    model_name: A-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 3
    model_name: B-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 4
    model_name: B
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 5
    model_name: B-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 6
    model_name: C-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 7
    model_name: C
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 8
    model_name: C-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 9
    model_name: D-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 10
    model_name: D
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 11
    model_name: D-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
- region_id: 1
  region_name: centralus_chiron
  region_cluster: dgx-a100
  arbiter: chiron_arbiter
  model_endpoints:
  - model_endpoint_id: 0
    model_name: A-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 1
    model_name: A
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 2
    model_name: A-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 3
    model_name: B-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 4
    model_name: B
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 5
    model_name: B-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 6
    model_name: C-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 7
    model_name: C
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 8
    model_name: C-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 9
    model_name: D-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 10
    model_name: D
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 11
    model_name: D-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
- region_id: 2
  region_name: eastus_chiron
  region_cluster: dgx-a100
  arbiter: chiron_arbiter
  model_endpoints:
  - model_endpoint_id: 0
    model_name: A-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 1
    model_name: A
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 2
    model_name: A-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 3
    model_name: B-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 4
    model_name: B
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 5
    model_name: B-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 6
    model_name: C-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 7
    model_name: C
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 8
    model_name: C-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 9
    model_name: D-p
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 20
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 10
    model_name: D
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
  - model_endpoint_id: 11
    model_name: D-d
    model_endpoint_router: chiron_round_robin
    start_state: orca
    instance_count: 10
    prompt_time: 10
    decode_throughput: 100
