power_budget: 232000

regions:
- region_id: 0
  region_name: westus
  region_cluster: dgx-a100
  arbiter: basic_arbiter
  model_endpoints:
  - model_endpoint_id: 0
    model_name: bloom-176b
    model_endpoint_router: round_robin
    start_state: orca
    instance_count: 40
  - model_endpoint_id: 1
    model_name: llama2-70b
    model_endpoint_router: round_robin
    start_state: orca
    instance_count: 40
- region_id: 1
  region_name: centralus
  region_cluster: dgx-a100
  arbiter: basic_arbiter
  model_endpoints:
  - model_endpoint_id: 0
    model_name: bloom-176b
    model_endpoint_router: round_robin
    start_state: orca
    instance_count: 40
  - model_endpoint_id: 1
    model_name: llama2-70b
    model_endpoint_router: round_robin
    start_state: orca
    instance_count: 40
- region_id: 2
  region_name: eastus
  region_cluster: dgx-a100
  arbiter: basic_arbiter
  model_endpoints:
  - model_endpoint_id: 0
    model_name: bloom-176b
    model_endpoint_router: round_robin
    start_state: orca
    instance_count: 40
  - model_endpoint_id: 1
    model_name: llama2-70b
    model_endpoint_router: round_robin
    start_state: orca
    instance_count: 40
