model_architecture: llama2-70b
model_size: llama2-70b-fp16
allocator: noop
scheduler: token_jsq
processor_affinity: a100
processor_count: 8
overheads: {}
debug: default.debug
_target_: application.Application
